spring.application.name=secure-password-manager
# AES encryption key (16 / 24 / 32 chars)
aes.secret.key=MySuperSecretKey1234567890ABCDEF

# JWT secret key (minimum 32 chars)
jwt.secret.key=my-super-secret-jwt-key-my-super-secret-jwt-key
jwt.expiration.ms=3600000
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
